# Generated by Django 6.0.5 on 2026-05-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_created_by_alter_seller_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='code',
            field=models.CharField(default='S00000', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
